{% set name = "smvs" %}
{% set version = "master" %}
{% set commit = "7cf59084329d494068c67bd57bfeae5660584ad3" %}
{% set mve_version = "master" %}
{% set mve_commit = "55eb94f34f82694e0f25a7f235c25a06acc0bfae" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/flanggut/smvs/archive/{{ commit }}.tar.gz
    sha256: 1236dd55b4c35dd43ff8943d01b5305d2369033d2f30ed938a2ce3310a7f81c4
    folder: {{ name }}
  - fn: mve-{{ mve_version }}.tar.gz
    url: https://github.com/simonfuhrmann/mve/archive/{{ mve_commit }}.tar.gz
    sha256: a1880f243b38ec0b669aa638225e45f300c508e621b1ee0fb3d444a665a512cc
    folder: mve

build:
    number: 0

requirements:
  # build:
    # - {{ compiler("c") }}
    # - {{ compiler("cxx") }}
  host:
    - mve {{ mve }}

test:
  commands:
    - test -f $PREFIX/bin/smvsrecon
    - test -f $PREFIX/lib/libsmvs.a

about:
  home: https://github.com/flanggut/smvs
  summary: Shading-aware Multi-view Stereo

extra:
  recipe-maintainers:
    - v-turin
